### ISSUE TITLE
Got error after adding depedancies

### ISSUE THREAD

**Issue by ucaresachinadhav** [bounceshare/clevertap_flutter#1]
Got error after adding depedancies and build project? Can you please help me.

/home/sachin/AndroidStudioProjects/clevertap_app/android/app/src/debug/AndroidManifest.xml:10:9-57 Error:
	Attribute application@name value=(io.flutter.app.FlutterApplication) from AndroidManifest.xml:10:9-57
	is also present at [:clevertap_flutter] AndroidManifest.xml:7:18-87 value=(com.bounceshare.clevertap_flutter.ClevertapApplication).
	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:9:5-41:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@name value=(io.flutter.app.FlutterApplication) from AndroidManifest.xml:10:9-57
  	is also present at [:clevertap_flutter] AndroidManifest.xml:7:18-87 value=(com.bounceshare.clevertap_flutter.ClevertapApplication).
  	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:9:5-41:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by PoojaB26** [comment]
Can you post the AndroidManifest code here?

**Comment by ucaresachinadhav** [comment]
> Can you post the AndroidManifest code here?

Thank you for response.

I got solution. Simply remove **android:name="io.flutter.app.FlutterApplication"** from your <application>
